-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 16:04:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `db_Ecommerce` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Ecommerce`.`tb_Produtos` (
  `idtb_Produtos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idtb_Produtos`),
  UNIQUE INDEX `idtb_Produtos_UNIQUE` (`idtb_Produtos` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_Ecommerce.tb_Produtos (Nome, Preco)
VALUES
("Caixa CPU",150.00),
("Processador",700.00),
("Placa de Memoria",400.00),
("SSD",300.00),
("Fonte",200.00),
("Placa Mãe",600.00),
("Monitor",400.00),
("Placa de Video",1200.00);

SELECT * FROM tb_Produtos where preco > 500.00;

SELECT * FROM tb_Produtos where preco <= 500.00;

UPDATE db_Ecommerce.tb_Produtos
SET Preco = 800.00
WHERE Nome = "Placa de memoria";



