-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 17:28:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Escola` DEFAULT CHARACTER SET utf8 ;
USE `db_Escola` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Escola`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Nota` INT NOT NULL,
  PRIMARY KEY (`idAlunos`),
  UNIQUE INDEX `idAlunos_UNIQUE` (`idAlunos` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_Escola.Alunos (Nome, Nota)
VALUES
("Khalesi",10),
("Sansa",6),
("Jon Snow",8),
("Arya",9),
("Ned Stark",7),
("Tyrion",5),
("Mindinho",3),
("Drogon",2);

SELECT * FROM db_Escola.Alunos WHERE Nota >= 7;

SELECT * FROM db_Escola.Alunos WHERE Nota < 7;

UPDATE db_Escola.Alunos
SET Nota = 8
WHERE nome = "Tyrion";
