-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 21:23:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `idtb_personagem` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tribo` VARCHAR(45) NOT NULL,
  `Atk` INT NOT NULL,
  `Def` INT NOT NULL,
  `Mag` INT NOT NULL,
  UNIQUE INDEX `idtb_personagem_UNIQUE` (`idtb_personagem` ASC) VISIBLE,
  PRIMARY KEY (`idtb_personagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `idtb_classe` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NOT NULL,
  `Ataque` INT NOT NULL,
  `Magia` INT NOT NULL,
  `idtb_clas` INT NOT NULL,
  PRIMARY KEY (`idtb_classe`),
  UNIQUE INDEX `idtb_classe_UNIQUE` (`idtb_classe` ASC) VISIBLE,
  INDEX `fk_tb_classe_tb_personagem_idx` (`idtb_clas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_classe_tb_personagem`
    FOREIGN KEY (`idtb_clas`)
    REFERENCES `db_generation_game_online`.`tb_personagem` (`idtb_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_generation_game_online.tb_classe (idtb_clas, Categoria, Ataque, Magia)
VALUES
("Guerreiro", 1000, 0),
("Arqueiro", 500, 500),
("Mago", 0, 1000);

INSERT INTO db_generation_game_online.tb_personagem (Nome, Tribo, Atk, Def, Mag)
VALUES
(1, "Aragon","Humano",3000,2000,1000),
(1, "Gimli","Anão",2500,3000,500),
(2, "Lelolas","Elfo",2500,2500,1000),
(3, "Gandalf Cinzento","Mago",2500,1000,2000),
(1, "Frodo","Hobbit",500,500,1500),
(3, "Sauron","Elfo",5000,5000,5000),
(3, "Gandalf o Branco","Mago",2000,2000,4000),
(1, "Sam","Hobbit",1500,500,0);

SELECT * FROM db_generation_game_online.tb_classe;

SELECT * FROM db_generation_game_online.tb_personagem;

SELECT tb_personagem.Nome, tb_personagem.Tribo, tb_classe.Categoria
FROM tb_personagem
INNER JOIN tb_classe
ON idtb_personagem = idtb_personagem;







