-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 21:29:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `idtb_classe` INT NOT NULL AUTO_INCREMENT,
  `Soldado` INT NOT NULL,
  `Guerreiro` INT NOT NULL,
  `Caçador` INT NOT NULL,
  `Arqueiro` INT NOT NULL,
  `Feiticeiro` INT NOT NULL,
  `Wizard` INT NOT NULL,
  UNIQUE INDEX `idtb_classe_UNIQUE` (`idtb_classe` ASC) VISIBLE,
  PRIMARY KEY (`idtb_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `idtb_personagem` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tribo` VARCHAR(45) NOT NULL,
  `Atk` INT NOT NULL,
  `Def` INT NOT NULL,
  `Mag` INT NOT NULL,
  `tb_classe_idtb_classe` INT NOT NULL,
  UNIQUE INDEX `idtb_personagem_UNIQUE` (`idtb_personagem` ASC) VISIBLE,
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  PRIMARY KEY (`tb_classe_idtb_classe`),
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`tb_classe_idtb_classe`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`idtb_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_generation_game_online.tb_personagem ()
VALUES
("Aragon","Humano",3000,2000,1000),
("Gimli","Anão",2500,3000,500),
("Lelolas","Elfo",2500,2500,1000),
("Gandalf Cinzento","Mago",2500,1000,2000),
("Frodo","Hobbit",500,500,1500),
("Sauron","Elfo",5000,5000,5000),
("Gandalf o Branco","Mago",2000,2000,4000),
("Sam","Hobbit",1500,500,0);

INSERT INTO db_generation_game_online.tb_classe ()
VALUES











